[tools]
ruby = "3.4.2"
python = "latest"

[env]
_.file = "../civicpatchorg.env"

[tasks.dev]
run = """
docker compose up -d
"""

[tasks.shellin]
run = """
docker exec -it civicpatch_web bash
"""

[tasks.shell]
run = """
docker exec -it civicpatch_web
"""

[tasks.deploy]
run = """
./script/build-and-push.py
"""