services:
  web:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile.dev
    container_name: civicpatch_web
    working_dir: /workspace/civicpatch.org # Codespaces uses `/workspace/<repo-name>` as the default workspace directory
    volumes:
      - ..:/workspace/civicpatch.org # Mount the parent directory into the container
      - /workspace/civicpatch.org/node_modules # Avoid mounting node_modules directly
    ports:
      - "3000:3000"
      #- "3036:3036"
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: civicpatch
      POSTGRES_PASSWORD: development-password
      POSTGRES_DB: civicpatch_development
  db:
    image: postgis/postgis:17-3.5
    container_name: civicpatch_db
    restart: always
    environment:
      POSTGRES_USER: civicpatch
      POSTGRES_PASSWORD: development-password
      POSTGRES_DB: civicpatch_development
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  test_db:
    image: postgis/postgis:17-3.5
    container_name: civicpatch_test_db
    restart: always
    environment:
      POSTGRES_USER: civicpatch
      POSTGRES_PASSWORD: test-password
      POSTGRES_DB: civicpatch_test
    volumes:
      - testdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  pgdata:
  testdata:
  node_modules_volume: {}
