name: Deploy to civicpatch.org

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python3
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Push docker image
        env:
          DOCKER_USERNAME: witch
          CIVICPATCHORG_GITEA_DOCKER_TOKEN: ${{ secrets.CIVICPATCHORG_GITEA_DOCKER_TOKEN }} 
          REMOTELAB_WORKFLOW_TOKEN: ${{ secrets.REMOTELAB_WORKFLOW_TOKEN }}
        run: |
          ./scripts/build-and-push.py