name: Update Open Data

on:
  workflow_dispatch

jobs:
  update-open-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.2
          bundler-cache: true

      - name: Generate GitHub App Token
        id: generate-pipeline-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.GH_APP_BOT_PIPELINE_APP_ID }}
          private-key: ${{ secrets.GH_APP_BOT_PIPELINE_PRIVATE_KEY }}
      
      - name: Install dependencies
        run: |
          bundle install

      - name: Install GEOS C Library
        run: sudo apt-get update && sudo apt-get install -y libgeos-dev
      
      - name: Set Git Config
        run: |
          git config --global user.name "Civic Patch Pipeline Bot"
          git config --global user.email "civic-patch-pipeline-bot[bot]@users.noreply.github.com"
      
      - name: Create a new branch for changes
        run: |
          # Generate a unique branch name for this run
          BRANCH_NAME="pipeline-update-open-data-${{ github.run_id }}"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          git checkout -b $BRANCH_NAME

      - name: Update Open Data
        run: |
          bundle exec rake od:sync
      
      - name: Commit Changes
        run: |
          git add .
          git commit -m "Update Open Data"

      - name: Open a pull request
        env:
          GITHUB_TOKEN: ${{ steps.generate-pipeline-token.outputs.token }}
        run: |
          git push --set-upstream origin ${{ env.BRANCH_NAME }}
          COMMENT=$(
            cat <<EOF
          PR opened by the Open Data Update workflow - ${{ github.actor }}
          EOF
          )
          gh pr create \
            --base main \
            --head ${{ env.BRANCH_NAME }} \
            --title "Update Open Data" \
            --body "$COMMENT"
  